// Package swagger_aggregator Code generated by swaggo/swag. DO NOT EDIT
package swagger_aggregator

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/srodi/ebpf-server/issues",
            "email": "support@example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://github.com/srodi/ebpf-server/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/connection-summary": {
            "get": {
                "description": "Get count of connection events filtered by PID, command, and time window",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "connections"
                ],
                "summary": "Get connection statistics",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Process ID",
                        "name": "pid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Command name",
                        "name": "command",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Duration in seconds (default: 60)",
                        "name": "duration_seconds",
                        "in": "query"
                    },
                    {
                        "description": "Connection summary request (POST only)",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/api.ConnectionSummaryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Connection statistics",
                        "schema": {
                            "$ref": "#/definitions/api.ConnectionSummaryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Service unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Get count of connection events filtered by PID, command, and time window",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "connections"
                ],
                "summary": "Get connection statistics",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Process ID",
                        "name": "pid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Command name",
                        "name": "command",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Duration in seconds (default: 60)",
                        "name": "duration_seconds",
                        "in": "query"
                    },
                    {
                        "description": "Connection summary request (POST only)",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/api.ConnectionSummaryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Connection statistics",
                        "schema": {
                            "$ref": "#/definitions/api.ConnectionSummaryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Service unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/events": {
            "get": {
                "description": "Get events filtered by type, PID, command, time range, and limit",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Query events",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Event type (connection, packet_drop)",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Process ID",
                        "name": "pid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Command name",
                        "name": "command",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start time (RFC3339 format)",
                        "name": "since",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End time (RFC3339 format)",
                        "name": "until",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of events to return (default: 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Filtered events",
                        "schema": {
                            "$ref": "#/definitions/api.EventsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Service unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/events/ingest": {
            "post": {
                "description": "Accept events from eBPF agents for aggregation and storage",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Ingest events from agents",
                "parameters": [
                    {
                        "description": "Events to ingest",
                        "name": "events",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ingestion result",
                        "schema": {
                            "$ref": "#/definitions/internal_aggregator.IngestResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "Method not allowed",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/l7/webhook": {
            "post": {
                "description": "Ingests L7 telemetry (SSL/TLS, HTTP, DNS) from external sensors",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "l7"
                ],
                "summary": "Receive L7 webhook events",
                "parameters": [
                    {
                        "description": "Webhook payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/l7.WebhookPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/l7.WebhookIngestionResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid payload",
                        "schema": {
                            "$ref": "#/definitions/l7.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Duplicate batch",
                        "schema": {
                            "$ref": "#/definitions/l7.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Storage error",
                        "schema": {
                            "$ref": "#/definitions/l7.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/l7/webhook/stats": {
            "get": {
                "description": "Returns ingestion statistics for L7 webhooks",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "l7"
                ],
                "summary": "Get webhook receiver statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/l7.WebhookStatsResponse"
                        }
                    }
                }
            }
        },
        "/api/list-connections": {
            "get": {
                "description": "Get recent connection events grouped by PID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "connections"
                ],
                "summary": "List connection events",
                "responses": {
                    "200": {
                        "description": "Connection events",
                        "schema": {
                            "$ref": "#/definitions/api.ConnectionListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Service unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/list-packet-drops": {
            "get": {
                "description": "Get recent packet drop events grouped by PID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "packet_drops"
                ],
                "summary": "List packet drop events",
                "responses": {
                    "200": {
                        "description": "Packet drop events",
                        "schema": {
                            "$ref": "#/definitions/api.PacketDropListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Service unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/packet-drop-summary": {
            "get": {
                "description": "Get count of packet drop events filtered by PID, command, and time window",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "packet_drops"
                ],
                "summary": "Get packet drop statistics",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Process ID",
                        "name": "pid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Command name",
                        "name": "command",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Duration in seconds (default: 60)",
                        "name": "duration_seconds",
                        "in": "query"
                    },
                    {
                        "description": "Packet drop summary request (POST only)",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/api.PacketDropSummaryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Packet drop statistics",
                        "schema": {
                            "$ref": "#/definitions/api.PacketDropSummaryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Service unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Get count of packet drop events filtered by PID, command, and time window",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "packet_drops"
                ],
                "summary": "Get packet drop statistics",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Process ID",
                        "name": "pid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Command name",
                        "name": "command",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Duration in seconds (default: 60)",
                        "name": "duration_seconds",
                        "in": "query"
                    },
                    {
                        "description": "Packet drop summary request (POST only)",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/api.PacketDropSummaryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Packet drop statistics",
                        "schema": {
                            "$ref": "#/definitions/api.PacketDropSummaryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Service unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/programs": {
            "get": {
                "description": "Get the status and information of all loaded eBPF programs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "programs"
                ],
                "summary": "List eBPF programs",
                "responses": {
                    "200": {
                        "description": "List of eBPF programs",
                        "schema": {
                            "$ref": "#/definitions/api.ProgramsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Service unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/stats": {
            "get": {
                "description": "Retrieve statistics about event aggregation including counts by type and node",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stats"
                ],
                "summary": "Get aggregation statistics",
                "responses": {
                    "200": {
                        "description": "Aggregation statistics",
                        "schema": {
                            "$ref": "#/definitions/internal_aggregator.AggregationStatsResponse"
                        }
                    },
                    "405": {
                        "description": "Method not allowed",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Get the health status of the eBPF monitoring system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "Health status",
                        "schema": {
                            "$ref": "#/definitions/api.HealthResponse"
                        }
                    },
                    "503": {
                        "description": "Service unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.ConnectionListResponse": {
            "type": "object",
            "properties": {
                "events_by_pid": {
                    "description": "Events grouped by PID",
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {}
                    }
                },
                "query_time": {
                    "description": "Query timestamp",
                    "type": "string",
                    "example": "2023-01-01T12:00:00Z"
                },
                "total_events": {
                    "description": "Total number of events",
                    "type": "integer",
                    "example": 10
                },
                "total_pids": {
                    "description": "Number of unique PIDs",
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "api.ConnectionSummaryRequest": {
            "type": "object",
            "properties": {
                "command": {
                    "description": "Command name",
                    "type": "string",
                    "example": "curl"
                },
                "duration_seconds": {
                    "description": "Duration in seconds",
                    "type": "integer",
                    "example": 60
                },
                "pid": {
                    "description": "Process ID",
                    "type": "integer",
                    "example": 1234
                }
            }
        },
        "api.ConnectionSummaryResponse": {
            "type": "object",
            "properties": {
                "command": {
                    "description": "Command name",
                    "type": "string",
                    "example": "curl"
                },
                "count": {
                    "description": "Number of connection events",
                    "type": "integer",
                    "example": 5
                },
                "duration_seconds": {
                    "description": "Duration in seconds",
                    "type": "integer",
                    "example": 60
                },
                "pid": {
                    "description": "Process ID",
                    "type": "integer",
                    "example": 1234
                },
                "query_time": {
                    "description": "Query timestamp",
                    "type": "string",
                    "example": "2023-01-01T12:00:00Z"
                }
            }
        },
        "api.EventFilters": {
            "type": "object",
            "properties": {
                "command": {
                    "description": "Command filter",
                    "type": "string",
                    "example": "curl"
                },
                "limit": {
                    "description": "Limit filter",
                    "type": "integer",
                    "example": 100
                },
                "pid": {
                    "description": "Process ID filter",
                    "type": "integer",
                    "example": 1234
                },
                "since": {
                    "description": "Start time filter",
                    "type": "string",
                    "example": "2023-01-01T12:00:00Z"
                },
                "type": {
                    "description": "Event type filter",
                    "type": "string",
                    "example": "connection"
                },
                "until": {
                    "description": "End time filter",
                    "type": "string",
                    "example": "2023-01-01T13:00:00Z"
                }
            }
        },
        "api.EventsResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "description": "Number of events returned",
                    "type": "integer",
                    "example": 25
                },
                "events": {
                    "description": "List of events",
                    "type": "array",
                    "items": {}
                },
                "filters": {
                    "description": "Applied filters",
                    "allOf": [
                        {
                            "$ref": "#/definitions/api.EventFilters"
                        }
                    ]
                },
                "query_time": {
                    "description": "Query timestamp",
                    "type": "string",
                    "example": "2023-01-01T12:00:00Z"
                },
                "total_count": {
                    "description": "Total number of matching events",
                    "type": "integer",
                    "example": 150
                }
            }
        },
        "api.HealthResponse": {
            "type": "object",
            "properties": {
                "component": {
                    "description": "Component name",
                    "type": "string",
                    "example": "eBPF Monitor API"
                },
                "status": {
                    "description": "Service status",
                    "type": "string",
                    "example": "healthy"
                },
                "uptime": {
                    "description": "Service uptime",
                    "type": "string",
                    "example": "1h30m"
                },
                "version": {
                    "description": "API version",
                    "type": "string",
                    "example": "1.0.0"
                }
            }
        },
        "api.PacketDropListResponse": {
            "type": "object",
            "properties": {
                "events_by_pid": {
                    "description": "Events grouped by PID",
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {}
                    }
                },
                "query_time": {
                    "description": "Query timestamp",
                    "type": "string",
                    "example": "2023-01-01T12:00:00Z"
                },
                "total_events": {
                    "description": "Total number of events",
                    "type": "integer",
                    "example": 7
                },
                "total_pids": {
                    "description": "Number of unique PIDs",
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "api.PacketDropSummaryRequest": {
            "type": "object",
            "properties": {
                "command": {
                    "description": "Command name",
                    "type": "string",
                    "example": "nginx"
                },
                "duration_seconds": {
                    "description": "Duration in seconds",
                    "type": "integer",
                    "example": 60
                },
                "pid": {
                    "description": "Process ID",
                    "type": "integer",
                    "example": 1234
                }
            }
        },
        "api.PacketDropSummaryResponse": {
            "type": "object",
            "properties": {
                "command": {
                    "description": "Command name",
                    "type": "string",
                    "example": "nginx"
                },
                "count": {
                    "description": "Number of packet drop events",
                    "type": "integer",
                    "example": 3
                },
                "duration_seconds": {
                    "description": "Duration in seconds",
                    "type": "integer",
                    "example": 60
                },
                "pid": {
                    "description": "Process ID",
                    "type": "integer",
                    "example": 1234
                },
                "query_time": {
                    "description": "Query timestamp",
                    "type": "string",
                    "example": "2023-01-01T12:00:00Z"
                }
            }
        },
        "api.ProgramInfo": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "Program ID",
                    "type": "integer",
                    "example": 123
                },
                "name": {
                    "description": "Program name",
                    "type": "string",
                    "example": "connection_tracer"
                },
                "status": {
                    "description": "Program status",
                    "type": "string",
                    "example": "loaded"
                },
                "type": {
                    "description": "Program type",
                    "type": "string",
                    "example": "kprobe"
                }
            }
        },
        "api.ProgramsResponse": {
            "type": "object",
            "properties": {
                "programs": {
                    "description": "List of eBPF programs",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.ProgramInfo"
                    }
                },
                "query_time": {
                    "description": "Query timestamp",
                    "type": "string",
                    "example": "2023-01-01T12:00:00Z"
                },
                "total_count": {
                    "description": "Total number of programs",
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "internal_aggregator.AgentInfo": {
            "type": "object",
            "properties": {
                "event_count": {
                    "description": "Number of events from this agent",
                    "type": "integer",
                    "example": 2500
                },
                "last_seen": {
                    "description": "Last seen timestamp",
                    "type": "string",
                    "example": "2023-01-01T12:00:00Z"
                },
                "node_name": {
                    "description": "Node name",
                    "type": "string",
                    "example": "worker-1"
                },
                "programs": {
                    "description": "Programs running on this agent",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_aggregator.ProgramInfo"
                    }
                },
                "status": {
                    "description": "Agent status",
                    "type": "string",
                    "example": "active"
                }
            }
        },
        "internal_aggregator.AggregatedEventFilters": {
            "type": "object",
            "properties": {
                "limit": {
                    "description": "Limit filter",
                    "type": "integer",
                    "example": 100
                },
                "node": {
                    "description": "Node name filter",
                    "type": "string",
                    "example": "worker-1"
                },
                "since": {
                    "description": "Start time filter",
                    "type": "string",
                    "example": "2023-01-01T12:00:00Z"
                },
                "type": {
                    "description": "Event type filter",
                    "type": "string",
                    "example": "connection"
                },
                "until": {
                    "description": "End time filter",
                    "type": "string",
                    "example": "2023-01-01T13:00:00Z"
                }
            }
        },
        "internal_aggregator.AggregatedEventsResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "description": "Number of events returned",
                    "type": "integer",
                    "example": 50
                },
                "events": {
                    "description": "List of aggregated events",
                    "type": "array",
                    "items": {}
                },
                "filters": {
                    "description": "Applied filters",
                    "allOf": [
                        {
                            "$ref": "#/definitions/internal_aggregator.AggregatedEventFilters"
                        }
                    ]
                },
                "query_time": {
                    "description": "Query timestamp",
                    "type": "string",
                    "example": "2023-01-01T12:00:00Z"
                },
                "total_count": {
                    "description": "Total number of matching events",
                    "type": "integer",
                    "example": 1250
                }
            }
        },
        "internal_aggregator.AggregatedListResponse": {
            "type": "object",
            "properties": {
                "events_by_node": {
                    "description": "Event count by node",
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "events_by_pid": {
                    "description": "Events grouped by PID",
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {}
                    }
                },
                "query_time": {
                    "description": "Query timestamp",
                    "type": "string",
                    "example": "2023-01-01T12:00:00Z"
                },
                "total_events": {
                    "description": "Total number of events",
                    "type": "integer",
                    "example": 45
                },
                "total_nodes": {
                    "description": "Number of nodes with events",
                    "type": "integer",
                    "example": 3
                },
                "total_pids": {
                    "description": "Number of unique PIDs across all nodes",
                    "type": "integer",
                    "example": 8
                }
            }
        },
        "internal_aggregator.AggregatedSummaryResponse": {
            "type": "object",
            "properties": {
                "command": {
                    "description": "Command name (if filtered)",
                    "type": "string",
                    "example": "curl"
                },
                "count": {
                    "description": "Total count across all nodes",
                    "type": "integer",
                    "example": 15
                },
                "count_by_node": {
                    "description": "Count by node",
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "duration_seconds": {
                    "description": "Duration in seconds",
                    "type": "integer",
                    "example": 60
                },
                "pid": {
                    "description": "Process ID (if filtered)",
                    "type": "integer",
                    "example": 1234
                },
                "query_time": {
                    "description": "Query timestamp",
                    "type": "string",
                    "example": "2023-01-01T12:00:00Z"
                },
                "total_nodes": {
                    "description": "Number of nodes with events",
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "internal_aggregator.AggregationStatsResponse": {
            "type": "object",
            "properties": {
                "aggregation_start": {
                    "description": "When aggregation started",
                    "type": "string",
                    "example": "2023-01-01T10:00:00Z"
                },
                "connected_agents": {
                    "description": "Number of connected agents",
                    "type": "integer",
                    "example": 5
                },
                "events_by_node": {
                    "description": "Events grouped by node",
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer",
                        "format": "int64"
                    }
                },
                "events_by_type": {
                    "description": "Events grouped by type",
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer",
                        "format": "int64"
                    }
                },
                "last_event_time": {
                    "description": "Timestamp of last event",
                    "type": "string",
                    "example": "2023-01-01T12:00:00Z"
                },
                "query_time": {
                    "description": "Query timestamp",
                    "type": "string",
                    "example": "2023-01-01T12:00:00Z"
                },
                "total_events": {
                    "description": "Total events stored",
                    "type": "integer",
                    "example": 12500
                }
            }
        },
        "internal_aggregator.AggregatorProgramsResponse": {
            "type": "object",
            "properties": {
                "all_programs": {
                    "description": "All programs across agents",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_aggregator.ProgramInfo"
                    }
                },
                "connected_agents": {
                    "description": "List of connected agents",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_aggregator.AgentInfo"
                    }
                },
                "query_time": {
                    "description": "Query timestamp",
                    "type": "string",
                    "example": "2023-01-01T12:00:00Z"
                },
                "total_agents": {
                    "description": "Total number of agents",
                    "type": "integer",
                    "example": 3
                },
                "total_programs": {
                    "description": "Total number of programs",
                    "type": "integer",
                    "example": 6
                }
            }
        },
        "internal_aggregator.HealthCheck": {
            "type": "object",
            "properties": {
                "component": {
                    "type": "string"
                },
                "stats": {
                    "type": "object",
                    "additionalProperties": true
                },
                "status": {
                    "type": "string"
                },
                "uptime": {
                    "type": "string"
                }
            }
        },
        "internal_aggregator.IngestResponse": {
            "type": "object",
            "properties": {
                "events_processed": {
                    "description": "Number of events processed",
                    "type": "integer",
                    "example": 25
                },
                "message": {
                    "description": "Status message",
                    "type": "string",
                    "example": "Events ingested successfully"
                },
                "success": {
                    "description": "Ingestion success status",
                    "type": "boolean",
                    "example": true
                },
                "timestamp": {
                    "description": "Processing timestamp",
                    "type": "string",
                    "example": "2023-01-01T12:00:00Z"
                }
            }
        },
        "internal_aggregator.ProgramInfo": {
            "type": "object",
            "properties": {
                "event_count": {
                    "description": "Events generated by this program",
                    "type": "integer",
                    "example": 1250
                },
                "name": {
                    "description": "Program name",
                    "type": "string",
                    "example": "connection_tracer"
                },
                "node": {
                    "description": "Node where program is running",
                    "type": "string",
                    "example": "worker-1"
                },
                "status": {
                    "description": "Program status",
                    "type": "string",
                    "example": "active"
                },
                "type": {
                    "description": "Program type",
                    "type": "string",
                    "example": "kprobe"
                }
            }
        },
        "l7.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "HTTP error name",
                    "type": "string",
                    "example": "Bad Request"
                },
                "message": {
                    "description": "Error message",
                    "type": "string",
                    "example": "Invalid JSON format"
                },
                "timestamp": {
                    "description": "Error timestamp",
                    "type": "string",
                    "example": "2026-01-31T17:30:00Z"
                }
            }
        },
        "l7.WebhookCertificate": {
            "type": "object",
            "properties": {
                "expiry_ts": {
                    "description": "Expiration timestamp (Unix)",
                    "type": "integer"
                },
                "issuer_cn": {
                    "description": "Issuer Common Name",
                    "type": "string"
                },
                "issuer_sha256": {
                    "description": "Issuer certificate SHA256",
                    "type": "string"
                },
                "leaf_sha256": {
                    "description": "Leaf certificate SHA256",
                    "type": "string"
                },
                "public_key_sha256": {
                    "description": "Public key SHA256",
                    "type": "string"
                }
            }
        },
        "l7.WebhookEvent": {
            "type": "object",
            "properties": {
                "certificate": {
                    "description": "Certificate metadata",
                    "allOf": [
                        {
                            "$ref": "#/definitions/l7.WebhookCertificate"
                        }
                    ]
                },
                "direction": {
                    "description": "\"inbound\" or \"outbound\"",
                    "type": "string"
                },
                "dst_ip": {
                    "description": "Destination IP address",
                    "type": "string"
                },
                "dst_port": {
                    "description": "Destination port",
                    "type": "integer"
                },
                "event_type": {
                    "description": "Flow identification",
                    "type": "string"
                },
                "fingerprints": {
                    "description": "TLS fingerprints",
                    "allOf": [
                        {
                            "$ref": "#/definitions/l7.WebhookFingerprints"
                        }
                    ]
                },
                "flow_id": {
                    "description": "Human-readable flow identifier",
                    "type": "string"
                },
                "flow_key": {
                    "description": "Unique flow key for deduplication",
                    "type": "string"
                },
                "flow_start_ts": {
                    "description": "Flow start timestamp (ms)",
                    "type": "integer"
                },
                "ip_version": {
                    "description": "4 or 6",
                    "type": "integer"
                },
                "metadata": {
                    "description": "Backward compatibility (v1.0)",
                    "type": "object",
                    "additionalProperties": true
                },
                "observed_at": {
                    "description": "Observation timestamp (ms)",
                    "type": "integer"
                },
                "protocol": {
                    "description": "\"tcp\", \"udp\", \"quic\"",
                    "type": "string"
                },
                "src_ip": {
                    "description": "Network addresses",
                    "type": "string"
                },
                "src_port": {
                    "description": "Source port",
                    "type": "integer"
                },
                "stats": {
                    "description": "Statistics",
                    "allOf": [
                        {
                            "$ref": "#/definitions/l7.WebhookStats"
                        }
                    ]
                },
                "tls": {
                    "description": "L7 security metadata",
                    "allOf": [
                        {
                            "$ref": "#/definitions/l7.WebhookTLS"
                        }
                    ]
                },
                "verdict": {
                    "description": "Policy and verdict",
                    "allOf": [
                        {
                            "$ref": "#/definitions/l7.WebhookVerdict"
                        }
                    ]
                }
            }
        },
        "l7.WebhookFingerprints": {
            "type": "object",
            "properties": {
                "ja3": {
                    "description": "MD5-based fingerprint",
                    "type": "string"
                },
                "ja3_features": {
                    "description": "JA3 component breakdown",
                    "allOf": [
                        {
                            "$ref": "#/definitions/l7.WebhookJA3Features"
                        }
                    ]
                },
                "ja4": {
                    "description": "String-based fingerprint",
                    "type": "string"
                },
                "ja4_plus": {
                    "description": "SHA256-based fingerprint",
                    "type": "string"
                }
            }
        },
        "l7.WebhookIngestionResponse": {
            "type": "object",
            "properties": {
                "events_failed": {
                    "description": "Events that failed",
                    "type": "integer",
                    "example": 0
                },
                "events_processed": {
                    "description": "Events successfully processed",
                    "type": "integer",
                    "example": 42
                },
                "message": {
                    "description": "Status message",
                    "type": "string",
                    "example": "Processed 42/42 events from batch"
                },
                "schema_version": {
                    "description": "Schema version received",
                    "type": "string",
                    "example": "1.1"
                },
                "success": {
                    "description": "Success status",
                    "type": "boolean",
                    "example": true
                },
                "timestamp": {
                    "description": "Response timestamp",
                    "type": "string",
                    "example": "2026-01-31T17:30:00Z"
                },
                "total_events": {
                    "description": "Total events in payload",
                    "type": "integer",
                    "example": 42
                }
            }
        },
        "l7.WebhookJA3Features": {
            "type": "object",
            "properties": {
                "cipher_count": {
                    "description": "Number of ciphers",
                    "type": "integer"
                },
                "curve_count": {
                    "description": "Number of curves",
                    "type": "integer"
                },
                "extension_count": {
                    "description": "Number of extensions",
                    "type": "integer"
                },
                "point_formats": {
                    "description": "EC point formats count",
                    "type": "integer"
                }
            }
        },
        "l7.WebhookPayload": {
            "type": "object",
            "properties": {
                "batch_id": {
                    "description": "Batch deduplication ID",
                    "type": "string"
                },
                "events": {
                    "description": "Batch of events",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/l7.WebhookEvent"
                    }
                },
                "schema_version": {
                    "description": "Batch metadata",
                    "type": "string"
                },
                "sent_at": {
                    "description": "RFC3339 timestamp",
                    "type": "string"
                },
                "sequence": {
                    "description": "Monotonic sequence number",
                    "type": "integer"
                },
                "source": {
                    "description": "Sensor identifier",
                    "type": "string"
                },
                "source_instance": {
                    "description": "Instance identifier",
                    "type": "string"
                }
            }
        },
        "l7.WebhookQUIC": {
            "type": "object",
            "properties": {
                "dcid": {
                    "description": "Destination Connection ID",
                    "type": "string"
                }
            }
        },
        "l7.WebhookStats": {
            "type": "object",
            "properties": {
                "bytes": {
                    "description": "Total bytes transferred",
                    "type": "integer"
                },
                "duration_ms": {
                    "description": "Flow duration in milliseconds",
                    "type": "integer"
                },
                "extraction_latency_ms": {
                    "description": "Data extraction latency",
                    "type": "number"
                },
                "ingest_latency_ms": {
                    "description": "Ingestion latency",
                    "type": "number"
                },
                "packets": {
                    "description": "Total packets",
                    "type": "integer"
                },
                "sensor_latency_ms": {
                    "description": "Sensor processing latency",
                    "type": "number"
                }
            }
        },
        "l7.WebhookStatsResponse": {
            "type": "object",
            "properties": {
                "average_payload_size": {
                    "description": "Average payload size (bytes)",
                    "type": "integer",
                    "example": 28000
                },
                "duplicate_events": {
                    "description": "Duplicate events filtered",
                    "type": "integer",
                    "example": 0
                },
                "event_success_rate": {
                    "description": "Success rate (%)",
                    "type": "number",
                    "example": 99.67
                },
                "failed_events": {
                    "description": "Failed events",
                    "type": "integer",
                    "example": 150
                },
                "failed_payloads": {
                    "description": "Failed payloads",
                    "type": "integer",
                    "example": 5
                },
                "payload_success_rate": {
                    "description": "Success rate (%)",
                    "type": "number",
                    "example": 99.67
                },
                "query_time": {
                    "description": "Query timestamp",
                    "type": "string",
                    "example": "2026-01-31T17:30:00Z"
                },
                "total_events": {
                    "description": "Total events processed",
                    "type": "integer",
                    "example": 45000
                },
                "total_payloads": {
                    "description": "Total payloads received",
                    "type": "integer",
                    "example": 1500
                },
                "tracked_batches": {
                    "description": "Batches in dedup cache",
                    "type": "integer",
                    "example": 500
                }
            }
        },
        "l7.WebhookTLS": {
            "type": "object",
            "properties": {
                "alpn": {
                    "description": "Application-Layer Protocol Negotiation",
                    "type": "string"
                },
                "quic": {
                    "description": "QUIC-specific information",
                    "allOf": [
                        {
                            "$ref": "#/definitions/l7.WebhookQUIC"
                        }
                    ]
                },
                "sni": {
                    "description": "Server Name Indication",
                    "type": "string"
                },
                "version": {
                    "description": "TLS version (e.g., \"771\" for TLS 1.2)",
                    "type": "string"
                }
            }
        },
        "l7.WebhookVerdict": {
            "type": "object",
            "properties": {
                "action": {
                    "description": "\"allow\", \"deny\", \"log\"",
                    "type": "string"
                },
                "cert_mismatch_action": {
                    "description": "Action taken on mismatch",
                    "type": "string"
                },
                "cert_mismatch_reason": {
                    "description": "Reason for mismatch",
                    "type": "string"
                },
                "cert_validation_level": {
                    "description": "\"standard\", \"strict\", \"none\"",
                    "type": "string"
                },
                "priority": {
                    "description": "Rule priority",
                    "type": "integer"
                },
                "rule_id": {
                    "description": "Policy rule identifier",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "eBPF Event Aggregator API",
	Description:      "HTTP API for aggregating and querying eBPF events from multiple agents",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
